services:

  app:
    build: .
    container_name: isokohub_app
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: isokohub_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: isokohub
      MYSQL_USER: isokohub_user
      MYSQL_PASSWORD: isokohub123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: isokohub_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  dbdata: